<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJhK8Odd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJhK8Odd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJhK8Odd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJhK8Odd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJhK8Odd\App_KernelDevDebugContainer([
    'container.build_hash' => 'JhK8Odd',
    'container.build_id' => '0443147f',
    'container.build_time' => 1646744376,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJhK8Odd');
